INSERT INTO Missions VALUES ('Faire de la documentation technique / utilisateur.');
INSERT INTO Missions VALUES ('Refonte graphique.');
INSERT INTO Missions VALUES ('Sécurisation / Gestion des erreurs.');
INSERT INTO Missions VALUES ('Ajout de nouvelles fonctionnalités.');
INSERT INTO Missions VALUES ('Optimiser le code précédent.');
INSERT INTO Missions VALUES ('Conception graphique.');
INSERT INTO Missions VALUES ('Mise en place de Docker.');
INSERT INTO Missions VALUES ('Mise en place de l''infrastructure de l''application.');
INSERT INTO Missions VALUES ('Création de scripts de récupération de données.');
INSERT INTO Missions VALUES ('Création d''un script de manipulation de données.');
INSERT INTO Missions VALUES ('Création d''un script d''équivalence a partir de la manipulation des données effectuées.');
INSERT INTO Missions VALUES ('Refonte technique de l''application.');
INSERT INTO Missions VALUES ('Création des fonctionnalités de l''application.');
INSERT INTO Missions VALUES ('Analyse de la marque.');
INSERT INTO Missions VALUES ('Création d''une charte graphique.');
INSERT INTO Missions VALUES ('Création d''un logo.');
INSERT INTO Missions VALUES ('Conception de wireframe.');
INSERT INTO Missions VALUES ('Conception d''une maquette.');

INSERT INTO Missions VALUES ('Programmation Objet.');
INSERT INTO Missions VALUES ('Programmation Web (JavaScript, React, VueJS).');
INSERT INTO Missions VALUES ('Programmation Back-end (.NET, NodeJS, Symfony, Spring Boot, Ruby On Rails).');
INSERT INTO Missions VALUES ('Bases de données SQL et NoSQL (MySQL, MariaDB, MongoDB).');
INSERT INTO Missions VALUES ('Programmation mobile (React Native).');
INSERT INTO Missions VALUES ('Gestion de projet : Méthodes agiles (Scrum, Kanban).');
INSERT INTO Missions VALUES ('Cybersécurité.');
INSERT INTO Missions VALUES ('DevOps : Docker, Docker compose, Pipeline CI/CD.');
INSERT INTO Missions VALUES ('Webdesign - Ergonomie (avec Suite Adobe).');
INSERT INTO Missions VALUES ('Modelisation 3D (OpenInventor).');
INSERT INTO Missions VALUES ('Versionning et travaille collaboratif : Git.');

INSERT INTO Missions VALUES ('Programmation Web (HTML, CSS).');
INSERT INTO Missions VALUES ('Programmation Back-end (PHP, C#, Java).');
INSERT INTO Missions VALUES ('Bases de données SQL (MySQL).');
INSERT INTO Missions VALUES ('Programmation Android (Java).');
INSERT INTO Missions VALUES ('Scripting (Python, Bash).');
INSERT INTO Missions VALUES ('Administration Système : Linux.');
INSERT INTO Missions VALUES ('Virtualisation : VirtualBox.');
INSERT INTO Missions VALUES ('Testing (Unitaire).');
INSERT INTO Missions VALUES ('Reglementation sur le traitement des données (CNIL, RGPD).');
INSERT INTO Missions VALUES ('Création d''un plugin Wordpress.');